fix(indexer): trim contract address
usecannon/cannon pull request #1050
Opened 2024-05-21 14:56 UTC by saeta-eth

2024-05-22 09:41 UTC, FuzzB0t approved these changes

2024-05-22 12:19 UTC, dbeal-eth requested changes
to be effective, also need to set the address stored in the actual hash (a few lines lower than you already edited)

2024-05-30 16:28 UTC, mjlescano commented
@dbeal-eth could you re-review this one? 🙏

2024-06-29 04:59 UTC, dbeal-eth approved these changes

2024-07-01 18:48 UTC, merged