fix(builder): Allow var step to have duplicate output
usecannon/cannon pull request #1218
Opened 2024-07-24 08:12 UTC by FuzzB0t

fixes https://linear.app/usecannon/issue/CAN-406/fix-output-clash-on-var-steps-with-description

2024-07-24 15:19 UTC, dbeal-eth requested changes
i think this one definitely needs a test to verify this edge case doesn't reappear.

2024-07-24 15:19 UTC, dbeal-eth commented on packages/builder/src/definition.ts
> +            if (!this.dependencyFor.has(output) || action == 'setting' || action == 'var') {
use triple equals `===`. surprised the linter didnt pick this one up.

2024-08-02 01:51 UTC, dbeal-eth submitted a review, later dismissed
also still think we would benefit from specific, purpose built test, not in e2e, that verifies this capability on the `definition.ts` file.

2024-08-02 01:51 UTC, dbeal-eth commented on examples/sample-foundry-project/cannonfile.old.toml
> -[setting.value]
this file is specifically designed to test the behavior of the old `setting`s format and other things before those renaming changes, so changing from `setting` to `var` here is not a good idea

2024-08-06 14:43 UTC, mjlescano commented on packages/builder/src/definition.ts
> +            if (!this.dependencyFor.has(output) || action === 'setting' || action === 'var') {
This wouldn't work weird when having a `var` that uses another `var`? Meaning that it wont be able to find correctly the dependency?

2024-08-06 14:47 UTC, mjlescano approved these changes

2024-08-06 19:58 UTC, merged