fix(website): Rework deploy page
usecannon/cannon pull request #1305
Opened 2024-08-21 21:24 UTC by FuzzB0t

fixes https://linear.app/usecannon/issue/CAN-444/add-deployments-from-partial-deploy-file

2024-08-22 23:27 UTC, FuzzB0t commented on packages/cli/src/commandsConfig.ts
> +    options: [
Added chain id option to pin command because the pin command fails when trying to pin a package that was built on a live network

2024-08-26 21:55 UTC, mjlescano requested changes
Currently the UI is allowing you to just paster a cannonfile without a partial deployment file, which it shouldn't:
<img width="751" alt="Screenshot 2024-08-26 at 18 54 22" src="https://github.com/user-attachments/assets/522a9fa8-8597-46c4-a17e-65c31eae1401">

2024-08-27 14:48 UTC, mjlescano commented
When landing for the first time on the gitops deployment page, directly from the link or navigating, there's no radio button selected by default, when the first one should be selected:
<img width="1512" alt="Screenshot 2024-08-27 at 11 46 51" src="https://github.com/user-attachments/assets/73221d9e-3e80-4fbc-95ca-c8a380a47d28">

2024-08-27 14:59 UTC, mjlescano approved these changes

2024-08-27 15:28 UTC, merged