feat(website): CAN-479 - Refactor custom providers
usecannon/cannon pull request #1331
Opened 2024-08-30 20:18 UTC by nicosampler

This PR closes CAN-479.
closes https://linear.app/usecannon/issue/CAN-473/ui-is-not-using-the-configured-providers-from-the-settings-page

I've converted the `useProviders` hook to a Provider which exposes `useProviders`. 

Hopefully, this PR fixes the case of using custom providers not supported by viem.

2024-08-31 10:09 UTC, dbeal-eth commented
@nicosampler please check if this PR replaces or should be in tandem or what with this PR https://github.com/usecannon/cannon/pull/1330

2024-09-05 18:43 UTC, mjlescano commented
Chain selector is not showing the whole list:

<img width="1511" alt="Screenshot 2024-09-05 at 15 43 09" src="https://github.com/user-attachments/assets/22d0a689-2327-4c0e-91da-1f6da7dd50ff">

2024-09-05 18:59 UTC, mjlescano approved these changes

2024-09-05 19:05 UTC, mjlescano requested changes
Deploy page is not working with custom chains, e.g.: http://localhost:3000/deploy?chainId=2192&address=0xF5d66dC9B6963c61D7dacB1208145397cAc2e678

2024-09-05 19:20 UTC, mjlescano approved these changes

2024-09-05 19:21 UTC, merged