feat(website): CAN-474 link to navigate to a package.
usecannon/cannon pull request #1357
Opened 2024-09-05 20:16 UTC by nicosampler

navigate to a package using a <a> link.

Closes  #CAN-474

2024-09-06 14:40 UTC, noahlitvin requested changes
Can we make the entire row a link? Like `as={Link}` on the the Tr probably?

2024-09-09 09:29 UTC, dbeal-eth reviewed
Need background as to why we are doing this.

Also I want to confirm, this is still static-site compatible, right?

2024-09-09 21:27 UTC, mjlescano approved these changes

2024-09-11 20:08 UTC, noahlitvin approved these changes

2024-09-12 01:37 UTC, merged