fix(publish): chain id setup
usecannon/cannon pull request #1408
Opened 2024-09-23 18:52 UTC by mjlescano

2024-09-23 20:43 UTC, FuzzB0t approved these changes

2024-09-24 03:41 UTC, dbeal-eth requested changes

2024-09-24 03:41 UTC, dbeal-eth commented on .nx/workspace-data/d/server-process.json
> +{"processId":63247}
remove

2024-09-24 03:41 UTC, dbeal-eth commented on .nx/workspace-data/lockfile.hash
> +11580160284360395692
remove?

2024-09-24 03:41 UTC, dbeal-eth commented on packages/builder/src/steps/clone.ts
> +      chainId: runtime.chainId,
this is wrong. `clone` steps should be pulling from chain ID 13370 by default. This is as intended. Please undo.

2024-09-24 03:57 UTC, dbeal-eth commented
fix confirmed, going to merge this as is.

2024-09-24 03:57 UTC, dbeal-eth approved these changes

2024-09-24 04:05 UTC, merged