[WIP] Fix Onboarding
usecannon/cannon pull request #17
Opened 2022-07-16 23:51 UTC by noahlitvin

- [ ] Hitting an issue with `lerna link`, seems like I can't get the cli to build since it's not picking up the new helpers package.
- [ ] Test CLI after downgrading foundry
- [ ] Test hardhat plug-in after downgrading foundry

Couldn't identify the best command to load an older version to test. Should be something like this: https://github.com/foundry-rs/foundry/tree/master/foundryup (We need any release that has an earlier timestamp than `anvil 0.1.0 (37e4376 2022-07-16T00:05:51.565487Z)`)

2022-07-19 15:14 UTC, noahlitvin commented
Tried downgrading with `foundryup -C 94bfdb2` to test but got `error: `/Users/noahlitvin/.foundry/foundry-rs/foundry/anvil` is not a directory. --path must point to a directory containing a Cargo.toml file.
foundryup: command failed: cargo install --path ./anvil --bin anvil --locked --force --root /Users/noahlitvin/.foundry`

Other than testing (and fixing the CI test?) this should be all set.

2022-07-20 06:49 UTC, dbeal-eth requested changes
please review ci as well, the errors are certainly unusual now

2022-07-20 06:49 UTC, dbeal-eth commented on packages/cli/src/helpers.ts
> +  const MINIMUM_NIGHTLY_ANVIL_BUILD_TIMESTAMP = 1657679573421;
yay, though you can probably truncate that down to a second and add a comment clarifying what date we are referring to here

2022-07-20 06:49 UTC, dbeal-eth commented on packages/cli/src/helpers.ts
> +      message: 'Cannon requires Cargo (https://doc.rust-lang.org/cargo/). Install it now?',
cargo is probably actually not needed now that we have been upstreamed (cargo is a build tool used by rust, but you dont need to build anything). At least, its not needed by the synthetix cli anymore

2022-07-20 10:20 UTC, merged