Add Sepolia network
usecannon/cannon pull request #220
Opened 2023-05-30 07:12 UTC by mohammadranjbarz

Resolve #205

2023-05-30 18:17 UTC, dbeal-eth requested changes
looks like you got it! but the lint is failing

2023-05-31 07:34 UTC, dbeal-eth requested changes
got a chance to look a little closer. unfortunately there still seem to be some problems:
* lines 1119-1136 seem to be redundant of 1137-1150
* lines 1119-1136 include incorrect data

2023-05-31 07:38 UTC, mohammadranjbarz commented
> got a chance to look a little closer. unfortunately there still seem to be some problems:
> 
> * lines 1119-1136 seem to be redundant of 1137-1150
> * lines 1119-1136 include incorrect data

You are right, I forgot to remove redundant draft lines,  this PR just needs
```
  {
    name: 'Sepolia Network',
    chainId: 11155111,
    shortName: 'sepolia',
    chain: 'Sepolia',
    network: 'testnet',
    networkId: 11155111,
    nativeCurrency: { name: 'Sepolia Ether', symbol: 'sETH', decimals: 18 },
    rpc: ['https://rpc.sepolia.org', 'https://rpc2.sepolia.org', 'https://rpc.sepolia.online'],
    etherscanApi: 'https://api-sepolia.basescan.org/api',
    etherscanUrl: 'https://sepolia.etherscan.io',
    faucets: ['https://coinbase.com/faucets/ethereum-sepolia-faucet'],
    infoURL: 'https://sepolia.dev',
  },
```

2023-05-31 19:02 UTC, dbeal-eth approved these changes

2023-06-01 07:59 UTC, merged