Fix ipfs publish file
usecannon/cannon pull request #261
Opened 2023-06-22 16:06 UTC by mjlescano

Before, when running the `publish` using an `@ipfs:Qm...` reference, it would only try to publish the given file on the registry, but with this fix it first makes sure to download the tree of artifacts and upload it to the configured `publishIpfsUrl`:
<img width="817" alt="Screenshot 2023-06-22 at 18 04 18" src="https://github.com/usecannon/cannon/assets/558901/1c5f0dba-2084-456e-abb9-4b0b62a7bb1f">

2023-06-22 16:09 UTC, mjlescano commented on packages/cli/src/index.ts
> +      signer: p.signers[0] || p.provider,
This is necessary for the case that the user does not configure a signer, so, it will still be able to run Read operations

2023-06-25 07:09 UTC, aminlatifi requested changes

2023-06-25 07:09 UTC, aminlatifi commented on packages/builder/src/package.ts
> +    const newMiscUrl = await readStorage.putBlob(await readStorage.readBlob(deployInfo.miscUrl));
```suggestion
    const newMiscUrl = await publishStorage.putBlob(await readStorage.readBlob(deployInfo.miscUrl));
```
@mjlescano I am not well-versed on this, am I right?

2023-06-25 07:09 UTC, aminlatifi commented on packages/builder/src/package.ts
> +    let newMetaUrl = metaUrl;
Is this initialization required?

2023-06-25 07:09 UTC, aminlatifi commented on packages/builder/src/package.ts
> +    const newMiscUrl = await readStorage.putBlob(await readStorage.readBlob(deployInfo.miscUrl));
Besides, shouldn't we check the upload was successful?

2023-06-25 07:09 UTC, aminlatifi commented on packages/builder/src/package.ts
> +    }
Should we save the new MetaUrl somewhere in the copy deployInfo, to upload again?

2023-07-04 12:21 UTC, mjlescano commented
This is not going to be merged, as the `cannon publish` command using an ipfs file funcionality is going to be moved to a new `extract-link` command.

2023-07-04 12:21 UTC, closed without merging