Add estimated gas log in publish command
usecannon/cannon pull request #310
Opened 2023-07-12 08:33 UTC by mohammadranjbarz

related #20

2023-07-12 08:36 UTC, mohammadranjbarz commented on packages/cli/src/index.ts
> +    let recipient;
@noahlitvin  I didnt know how should I fill `contract`, `recipient` and is `contract.estimateGas.publish` right or not?

2023-07-20 12:47 UTC, mohammadranjbarz commented
@noahlitvin  It's ready for review now

<img width="1712" alt="Screen Shot 1402-04-29 at 15 29 10" src="https://github.com/usecannon/cannon/assets/9850545/e6d11880-b919-4156-abfd-f35c7b868526">
<img width="1574" alt="Screen Shot 1402-04-29 at 15 29 50" src="https://github.com/usecannon/cannon/assets/9850545/c7efb220-7a75-4887-b2d3-f80068d1d302">

https://goerli.etherscan.io/tx/0x9a16c2f3db1f23aae8f9e6a96fc4aea503d0e49f2d5e9cd70a78983ca1fba704

2023-07-20 12:53 UTC, dbeal-eth requested changes
Is there any other data we can print about the Multicall besides hust the gas estimate? For example, can we also print out the number of calls in the Multicall, the selected gas price, perhaps the list of packages included? I know it's not included on the original issue spec but this is not the only thing about publish loggigng that needs a revisit

2023-07-20 13:18 UTC, mohammadranjbarz commented
> Is there any other data we can print about the Multicall besides hust the gas estimate? For example, can we also print out the number of calls in the Multicall, the selected gas price, perhaps the list of packages included? I know it's not included on the original issue spec but this is not the only thing about publish loggigng that needs a revisit

@dbeal-eth  I don't have much experience in solidy so I don't know how much data we can have, you and @noahlitvin  @aminlatifi  can help me, if there is other data please tell me then I will try to achieve them

2023-07-24 15:57 UTC, mohammadranjbarz commented
@dbeal-eth 
I added more details in the logs, how is it now?

<img width="803" alt="Screen Shot 1402-05-02 at 19 25 43" src="https://github.com/usecannon/cannon/assets/9850545/9dae03d7-6115-4688-ba87-84519f91f1f5">

2023-07-24 18:03 UTC, aminlatifi requested changes

2023-07-24 18:03 UTC, aminlatifi commented on packages/builder/src/registry.ts
> +      const gasPrice = await this.provider?.getGasPrice();
Override values must be observed.

2023-07-25 01:17 UTC, dbeal-eth approved these changes
😆 ks great, see Amin comment

2023-07-25 09:21 UTC, mohammadranjbarz commented
@dbeal-eth  @aminlatifi 

Now I consider input maxFeePerGas

* When the user doesn't enter `--max-fee-per-gas`
<img width="1406" alt="Screen Shot 1402-05-03 at 12 43 26" src="https://github.com/usecannon/cannon/assets/9850545/d5e96672-e62a-404d-a377-157713f6feee">

* When the user enters `--max-fee-per-gas`
<img width="1440" alt="Screen Shot 1402-05-03 at 12 43 42" src="https://github.com/usecannon/cannon/assets/9850545/16663fcb-cab4-4188-b2db-503f998a179b">

2023-07-25 09:54 UTC, aminlatifi requested changes

2023-07-25 09:54 UTC, aminlatifi commented on packages/builder/src/registry.ts
> +      const gasPrice = (overrides.maxFeePerGas as BigNumber) || (await this.provider?.getGasPrice());
`overrides` can have `gasPrice` property as well which takes precedence over the network default value (obtained by provider.getGasPrice)

2023-07-27 05:18 UTC, dbeal-eth approved these changes

2023-07-29 06:38 UTC, merged