363 inspect disable interactive mode in ci env
usecannon/cannon pull request #364
Opened 2023-08-25 18:56 UTC by FuzzB0t

2023-08-27 17:37 UTC, dbeal-eth requested changes
PR title does not match contents

PR appears to be making change to allow for target to be an array or non-array, but the title states somethign completely different which isnt included.

2023-08-27 17:37 UTC, dbeal-eth commented on packages/builder/src/schemas.zod.ts
> +    message: `"${val}" must be a valid ethereum address, previously defined contract step name, contract artifact name or filepath`,
`previously defined contract step name` => `existing contract step name`

its not necessary that the contract step was "previous" (although it must be depended upon) (soon we are  getting rid of `depends` so probably just best to keep response simple)

2023-08-27 18:39 UTC, FuzzB0t commented
> PR title does not match contents
> 
> PR appears to be making change to allow for target to be an array or non-array, but the title states somethign completely different which isnt included.

Yeah this PR contains both changes, although somewhat irrelevant to eachother, I'll change the PR title to match the contents better.

2023-08-29 00:51 UTC, dbeal-eth approved these changes

2023-08-29 18:38 UTC, merged