Fixed some unit tests and fixed yarn link on snx tests
usecannon/cannon pull request #746
Opened 2024-02-01 02:20 UTC by FuzzB0t

This PR adds some fixes to the unit and e2e tests + adds fixes to snx ci

2024-02-07 04:03 UTC, FuzzB0t commented on packages/cli/test/e2e/scripts/non-interactive/downstream-ci-synthetix-v3.sh
> +yarn link $CANNON_REPO_DIR/packages/hardhat-cannon
When the builder `yarn link` fails due to circular dependencies between packages.

2024-02-07 04:16 UTC, FuzzB0t commented on packages/cli/test/e2e/scripts/non-interactive/downstream-ci-synthetix-v3.sh
> +yarn link $CANNON_REPO_DIR/packages/hardhat-cannon
I think its necessary technically as part of the test to cover all of the packages but still need to work through how to set that up.

2024-02-08 11:59 UTC, dbeal-eth requested changes

2024-02-08 11:59 UTC, dbeal-eth commented on packages/cli/test/e2e/scripts/non-interactive/downstream-ci-synthetix-v3.sh
> +yarn link $CANNON_REPO_DIR/packages/hardhat-cannon
I think running `yarn link` before running `yarn` may erase the previously set `link`s... can you confirm this is not the case?

2024-02-08 11:59 UTC, dbeal-eth commented
also, some of hte tests still appear to be failing on ci. is there anything we can do to improve this?

2024-02-09 15:09 UTC, FuzzB0t commented on packages/cli/test/e2e/scripts/non-interactive/downstream-ci-synthetix-v3.sh
> +yarn link $CANNON_REPO_DIR/packages/hardhat-cannon
I dont think `yarn link` will break previous links. Each linked package is managed independently, so linking one package shouldn't interfere with links to other packages.

2024-02-12 01:36 UTC, dbeal-eth approved these changes

2024-02-12 04:18 UTC, merged